version: "3"
services:
  express-server:
    build: ./projet-vuejs-dawin-backend
    command: nodemon server.js
    volumes:
      - ./projet-vuejs-dawin-backend:/app/api
      - ./projet-vuejs-dawin-backend/node_modules:/app/api/node_modules
    ports:
      - "3000:3000"
    links:
      - mongo
  vue:
    build: ./projet-vuejs-dawin-frontend
    volumes:
      - ./projet-vuejs-dawin-frontend:/app/ui
      - ./projet-vuejs-dawin-frontend/node_modules:/app/ui/node_modules
    ports:
      - "8080:8080"
    links:
      - express-server
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db:Z
    ports:
      - "27017:27017"
