version: "3"
services:
  express-server:
    build: ./projet-vuejs-dawin-backend
    command: nodemon server.js
    volumes:
      - ./projet-vuejs-dawin-backend:/app/api
      - ./projet-vuejs-dawin-backend/node_modules:/app/api/node_modules
    ports:
      - "3000:3000"
  vue:
    build: ./projet-vuejs-dawin-frontend
    volumes:
      - ./projet-vuejs-dawin-frontend:/app/ui
      - ./projet-vuejs-dawin-frontend/node_modules:/app/ui/node_modules
    ports:
      - "8080:8080"
